config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  # GET /
  root to: "home#index"
  get 'about', to: "home#about"
  get ':username', to: "users#show", as: :user
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
=begin
email:string
password_digest: string

has_secured_password add virtual attributes
password:string virtual
password_confirmation:string virtual
=end
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :socials, dependent: :delete_all
  has_one_attached :image
  accepts_nested_attributes_for :socials, reject_if: proc { |attributes| attributes['name'].blank? || attributes['link'].blank?}
  VALID_USERNAME_REGEX = /\A[\w]+/
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       format: { with: VALID_USERNAME_REGEX }
  validates :name, presence: true, length: { maximum: 50 } 
  validate :image_type_validation
  
  def social_media(social_media = nil)
    links = []
    if social_media
      social_media.each { |social| links.push(social.link)}
      return links.join(", ")
    end
    ""
  end

  private

  def image_type_validation
    valid_types = ["image/png", "image/jpeg"]
    if image.attached? && !image.content_type.in?(valid_types)
      errors.add(:image, "must be a JPEG or PNG file.")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
=begin
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :description])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :image, socials_attributes: [:id, :name, :link]])
  end
=end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.all
  end

  def create
    @user = User.new(user_param)
    if @user.save
      redirect_to profiles_path
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private
  def user_param
    params.require(:user).permit(:email, :username, :firstname, :lastname, :bio, :socialmedia, :password, :password_confirmation)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    current_user.socials.build
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [:name, :description, :image,
                                        socials_attributes: [:id, :name, :link]])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!, only: [:edit, :update]

  def show
    @user = User.find_by(username: params[:username])
    unless @user
      flash[:alert] = "No profile for that Username or it's a private profile"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<h1>About Profiles</h1>
<div>
    <p>
        Want to connect with people from all over the world?
    </p>
    <p>
        Try Profiles. Create your own and start connecting ...
    </p>
    <%= link_to 'Sing Up', new_user_registration_path %>
<div>

app/views/home/index.html.erb
<h1>Welcome to Profiles</h1>
<div class="introduction">
    <p>
        Want to connect with people from all over the world?
    </p>
    <p>
        Try Profiles. Create your own and start connecting ...
    </p>
<div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% case name %>
  <% when "alert" %>
    <% context = "warning" %>
  <% when "notice" %>
    <% context = "success" %>
  <% else %>
    <% context = "light" %>
  <% end %>
  <div class="alert alert-<%= context %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Profiles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- Navbar -->
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>Profiles List</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Social Media</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= "#{user.firstname} #{user.lastname}" %></td>
        <td><%= user.bio %></td>
        <td><%= user.socialmedia %></td>
        <td><%= link_to 'Show', profile_path(user) %></td>
        <td><%= link_to 'Edit', profiles_path %></td>
        <td><%= link_to 'Destroy', profiles_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Profile", new_profile_path %>

app/views/profiles/list.html.erb
<h1>Profiles List</h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Social Media</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= "#{user.firstname} #{user.lastname}" %></td>
        <td><%= user.bio %></td>
        <td><%= user.socialmedia %></td>
        <td><%= link_to 'Show', "/show/#{user.id}" %></td>
        <td><%= link_to 'Edit', list_path %></td>
        <td><%= link_to 'Destroy', list_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= form_with model: @user, url:profiles_path do |form| %>
  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, class: "form-control", placeholder: "user@example.com" %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :username, class: "form-label" %>
    <%= form.text_field :username, class: "form-control", placeholder: "Niceguy" %>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :firstname, "First Name", class: "form-label" %>
    <%= form.text_field :firstname, class: "form-control", placeholder: "Your First Name Here" %>
    <% @user.errors.full_messages_for(:firstname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :lastname, "Last Name", class: "form-label" %>
    <%= form.text_field :lastname, class: "form-control", placeholder: "Your Last Name Here" %>
    <% @user.errors.full_messages_for(:lastname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :bio, class: "form-label" %>
    <%= form.text_field :bio, class: "form-control", placeholder: "I am a nice guy" %>
    <% @user.errors.full_messages_for(:bio).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :socialmedia, "Social Media", class: "form-label" %>
    <%= form.text_field :socialmedia, class: "form-control", placeholder: "twitter.com/Niceguy" %>
    <% @user.errors.full_messages_for(:socialmedia).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :password, class: "form-label" %>
    <%= form.password_field :password, class: "form-control", placeholder: "Your Password Here" %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div class="mb-3">
    <%= form.label :password_confirmation, class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Your Password Here" %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit "Send", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<h1>Show Profile</h1>

<div>
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input type="text" id="email" class="form-control", value="<%= @user.email %>">
  </div>
  <div class="mb-3">
    <label for="username" class="form-label">Username</label>
    <input type="text" id="username" class="form-control", value="<%= @user.username %>">
  </div>
  <div class="mb-3">
    <label for="firstname" class="form-label">First Name</label>
    <input type="text" id="firstname" class="form-control", value="<%= @user.firstname %>">
  </div>
  <div class="mb-3">
    <label for="lastname" class="form-label">Last Name</label>
    <input type="text" id="lastname" class="form-control", value="<%= @user.lastname %>">
  </div>
  <div class="mb-3">
    <label for="bio" class="form-label">Bio</label>
    <input type="text" id="bio" class="form-control", value="<%= @user.bio %>">
  </div>
  <div class="mb-3">
    <label for="socialmedia" class="form-label">Social media</label>
    <input type="text" id="socialmedia" class="form-control", value="<%= @user.socialmedia %>">
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Profiles</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Show profile", user_path(current_user.username), class: "dropdown-item" %>
              <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/shared/_add_social.html.erb
  <%= f.label :name, "Name", class: "form-label" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :link, "Link", class: "form-label" %>
  <%= f.text_field :link, class: "form-control" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>

<div>
  <% if @user.image.attached? %>
    Picture
    <div class="mb-3">
      <%= link_to image_tag(@user.image.variant(resize_to_limit: [400, 400])), @user.image, target: "_blank" %>
    </div>
  <% end %>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <input type="text" id="name" class="form-control", value="<%= @user.name %>">
  </div>
  <% if @user.description %>
    <div class="mb-3">
      <label for="description" class="form-label">Description</label>
      <input type="text" id="description" class="form-control", value="<%= @user.description %>">
    </div>
  <% end %>
  <% unless @user.socials.empty? %>
    <div class="mb-3">Social Media
      <% @user.socials.each do |social| %>
        <div class="mb-3">
          <label for="social_name<%= social.id %>" class="form-label">Name</label>
          <input type="text" id="social_name<%= social.id %>" class="form-control", value="<%= social.name %>">
        </div>
        <div class="mb-3">
          <label for="social_link<%= social.id %>" class="form-label">Link</label>
          <input type="text" id="social_link<%= social.id %>" class="form-control", value="<%= social.link %>">
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<% if current_user == @user %>
  <div>
    <%= link_to "Edit", edit_user_registration_path %>
  </div>
<% end %>